---
title: "Archaeal tree"
author: "Calla Bush St George"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: show
    theme: spacelab
    highlight: pygments
    keep_md: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
  keep_md: true  
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "../figures/archaea/") #Send any figure output to this folder
```

## Before you start

### Set my seed
```{r set seed}
# Any number can be chose
set.seed(567890)
```

### Load Libraries

```{r load-libraries}
# Efficient package loading with pacman 
pacman::p_load(tidyverse, ggtree, ggtext, mdthemes,phyloseq, phytools,
               install = FALSE)
```

```{r load-tree}
# Tree is RAxML in newick format
tree <- 
  read.tree("data/2024_03_27_Archaea.newick")
tree

```

```{r view-tree}
tree_plot <-
  ggplot(tree) + geom_tree() + theme_tree()

tree_plot

# add a scale
tree_scale_df <-
  ggtree(tree) + geom_treescale()
tree_scale_df

# Label the tips
tree_scale_df + geom_tiplab(size = 2) + ggplot2::xlim(0, 0.)

```

